### PR TITLE
added tutorial 2

### PR DESCRIPTION
**Pull request by GTimothee**

### CODE REVIEW

**Review by glatard — COMMENTED** [review]
Thanks for this! What are the .fdb_latexmk and other related files? They don't seem to belong here.

**Comment by GTimothee** [comment]
I don't know maybe it is when my "atom" plugin is generating the pdf file from the latex file. I will remove it.

**Comment by GTimothee** [comment]
I think this time it is OK. My branch is up-to-date and I removed unuseful files.

**Comment by glatard** [comment]
perfect, thanks!

**Pull request merged**
